version: '2'

services:
  exam:
    depends_on:
      - rdb
      - hotline
    build: "./test"
#   volumes:
#     - "/home/docker/dev/test:/usr/local/src/test"
    links:
      - "rdb:rdb"
      - "hotline:hotline"
    environment:
      PG_USER: postgres
      PG_PASS: postgres
      PG_NAME: hotline
      PG_HOST: rdb
      PG_PORT: 5432
      PGPASSWORD: postgres
      APP_HOST: hotline
      APP_PORT: 3000
    command: "dockerize -timeout 60s -wait tcp://rdb:5432 npm run test"
  hotline:
    depends_on:
      - rdb
    build: "./node"
    ports:
      - "8080:3000"
#   volumes:
#     - "/home/docker/dev/node:/usr/local/src/hotline"
    links:
      - "rdb:rdb"
    environment:
      PORT: 3000
      NODE_ENV: develop
      SESSION_SECRET: secret
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_NAME: hotline
      PG_HOST: rdb
      PG_PORT: 5432
      SENDER_EMAIL: "mailto:motojouya@gmail.com"
      MAIL_SERVICE:
      MAIL_USER:
      MAIL_PASS:
      MAIL_PORT:
      MAIL_FROM:
      MAIL_HOST:
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      AWS_REGION:
      S3_BUCKET:
  rdb:
    build: "./rdb"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotline
    ports:
      - "5432:5432"

